### ISSUE TITLE
as_geos_geometry() method for sfg objects

### ISSUE THREAD

**Issue by JosiahParry** [paleolimbot/geos#82]
Title says it all. I like to subset sfc objects and pass them into geos. I will always use `[[` for subsetting, get the error `no applicable method for 'as_geos_geometry' applied to an object of class "c('XY', 'POLYGON', 'sfg')"`, remove a level of brackets and do it again.

I suggest the following implementation.

```r
as_geos_geometry.sfg <- function(x) {
  geos_read_wkb(list(sf::st_as_binary(x)), crs = NA)
}
```

I'd make a PR but I can't find the source code for the sf methods!

**Comment by davilaaDEV** [comment]
have you solved your issue?

**Comment by JosiahParry** [comment]
@davilaaDEV Hm?

**Comment by JosiahParry** [comment]
I've updated my version of geos and all is well! It appears that the default method now handles this and delegates the work out to {wk}. It has a method for sfc but not sfg. The magic continues
